### ISSUE TITLE
Refactor into sub-components that allow reuse of elements such as the logo

### ISSUE THREAD

**Issue by brylie** [creativecommons/cc-global-components#22]
We agreed in issue #12 that it might be good to eventually refactor the CC Global Components into smaller components, allowing the re-use of code such as the CC logo.

## Original discussion
> As a thought experiment, what if we refactor the `cc-global-components` project in a way that encapsulates the above mockup into three sub-components and one parent component composed of the children?
> 
> ![image](https://user-images.githubusercontent.com/17307/145800520-2dd41933-32ce-47f4-b5ea-a2626cc43343.png)
> 
> One benefit of the above component structure might be that we can re-use the `cc-logo` component within the Explore CC component to reduce our bundle size #11

This will be a better approach, and we'll be potentially reducing the number of issues especially as concerns overlapping content.
I'll do a quick prototype asap.

_Originally posted by @MuluhGodson in https://github.com/creativecommons/cc-global-components/issues/12#issuecomment-992350875_

## Task

- [ ] determine the best way to organize the CC Global Components code for re-use and to minimize the bundle size
- [ ] discuss trade-offs with possible solutions
- [ ] refactor the project based on the discussion outcome

## Caveats

- the localization drop-down should not be included in the Explore CC component
  - localization will be done on a per-project basis and will be considered for the WordPress project post-MVP
- downstream developers should be able to place page elements, such as the Donate button, adjacent to the Explore CC tab
- downstream projects will use a different logo than the primary creativecommons.org logo depicted in the mockup
- for the time being, we can rely on Bulma semantics in downstream projects to control layout, so the CC Global Components should generally be layout agnostic

**Comment by MuluhGodson** [comment]
>
>@MuluhGodson this is correct. The various web properties to which we link from the CC Global Header will mostly have their >own logo and their own header navigation.
>
>You can see examples of initial implementation on e.g. the CC Open Source site (opensource.creativecommons.org). While we >do not need to change that implementation now, it is something we will need to rework after the MVP launch of >CreativeCommons.org
>
>There are several other sites in the CC suite, all of which will run on their own instance of WordPress (such as CC Summit, CC >Certificates, CC Global Network), and in those instances it may be more complex to populate the header navigation via a >global component. This will depend on how we end up rebuilding those sites in 2022.

Original [comment](https://github.com/creativecommons/project_creativecommons.org/issues/149#issuecomment-993538956) by @annatuma 


Here is a little screen-record of a possible implementation for the `cc-logo` component.
Keeping in mind that this component should be able to render a different logo depending on which CC service it is mounted on.

As of now, there are 10 different logos attributed to the different CC services. 
- Creative Commons: `cc-cc`
- CC Certificate: `cc-certificate`
- CC Chooser: `cc-chooser`
- CC Global Network: `cc-global-network`
- CC Global Summit: `cc-global-summit`
- CC Legal Database: `cc-legal-database`
- CC Open Source: `cc-open-source`
- CC Search: `cc-search` =========> now CC OpenVerse
- CC State of the Commons: `cc-state-of-the-commons`
- CC vocabulary: `cc-vocabulary`

I went to Figma and downloaded each of the logos as `svg` files to use for this demonstration. It can potentially work with any image types (pngs, jpgs etc) but I'm sure we'll stick with SVGs given its scalability advantages without losing quality and being able to style them with CSS.  Good thing is these SVG's already exist online.

With this, I did a basic component that takes an attribute, `site`, then renders the corresponding logo.
Example: to render the CC Chooser logo:
```html
<div  id="logo-cc">
    <cc-logo site="chooser" />
</div>
```

https://user-images.githubusercontent.com/40151808/146073759-91678795-12d4-4072-878b-a110a87d60cb.mp4



/////// Adding the underlying code here so when this issue is revisited we can have something to work from: 

```html
<template>
    <div>
        <a href="/" aria-label="home" class="main-logo margin-bottom-bigger columns">
            <div class="has-text-black column is-half">
                <img :src="`/assets/${logoPath}`" :alt="logoPath">
            </div>
        </a>
    </div>
</template>
<script>
import { defineComponent } from "vue";
export default defineComponent({
    name: "cc-logo",
    props: {
        site: {
            type: String,
            required: true,
            default: "cc"
        },
    },
    computed: {
        logoPath() {
            return this.site + ".svg"
        }
    }
});
</script>
<style scoped>

</style>
```

**Comment by MuluhGodson** [comment]
>
>CreativeCommons.org = has multiple things happening under the hood, all should have the same site navigation
>CC Summit = has its own logo and site navigation
>CC Certificates = in the future, will have its own logo and site navigation, might have multiple different things happening behind >the scenes (i.e. base site may be WordPress, the course content may be on a different education-specific publishing platform, >tbd)
>... and so forth.
>

Original comment can be found [here](https://github.com/creativecommons/cc-global-components/issues/12#issuecomment-993554354) by @annatuma 


For the `cc-nav` component which will render the Menu items, one approach to look at could be this:
Let's note the points below.
- Most/all main CC sites run on Wordpress e.g ([creativecommons.org](creativecommons.org), [summit.creativecommons.org](summit.creativecommons.org) etc)
- The CC sites that don't run on Wordpress will most likely render a Menu from a main CC site e.g Licenses which runs on Django will take its menu from `creativecommons.org`

Currently the `CC Global Header` which is what renders the menus does the API calls and then loops over the response and displays the menu items. 
One good thing is, no matter the CC site, they all have the same type of styling for the menu (fonts, colors etc)

Now let's examine the API endpoint that returns the menu items for `project_creativecommons.org`:

```html
<cc-global-header  base-url="creativecommons.org"  />
```

- we have a `base-url`: `creativecommons.org`
and in the background
- we have a `request-path`: `/?rest_route=/ccnavigation-header/menu`

The focus here will be to have this `request-path` configured in the other cc sites (which can be done for both Wordpress powered sites and Non-Wordpress sites which will have their own specific menus). 

With this, given that we have the same `request-path` no matter the CC site, we can just change the `base-url` and get the desired menu we need which will be rendered with the same styles etc. 

Example say we wanted to render the menu items for the Summit website on another service, we could just easily mount the `cc-nav` component as

```html
<cc-nav base-url="summit.creativecommons.org" />
```
which will then have as `request-url`: `summit.creativecommons.org/?rest_route=/ccnavigation-header/menu`

With this approach, we would potentially be able to display any menu items from any of the services on any other website. 

For a website that doesn't run on WordPress, we would ideally create a REST API for it with the same endpoint and have it return a JSON response and with that we can also be able to call it via the `cc-nav` component. 


With this, combined with the `cc-logo` component demonstrated above we can be able to render the correct Headers for any of the services.
Example, say we wanted a header for the Chooser website with it's menu items gotten from the Summit website, we could then do: 

```html
<div class="container"
   <div class="is-flex is-justify-content-between">
        <div id="mount-logo">
            <cc-logo site="chooser" />     ===========> Logo component
        </div>
        <div id="mount-nav">
            <cc-nav base-url="summit.creativecommons.org" /> ================> Nav component
        </div>
    </div>
</div>
```

With this, if someday we wanted to display different Nav items from a different CC website, we would ideally just change the `base-url` for the `cc-nav` component and we are good to go.

**Comment by brylie** [comment]
@MuluhGodson, how do the added SVG logos affect our bundle size? I'm wondering, might the logo files be included in the downstream project and passed to the `cc-logo` component as an argument? What would be some trade-offs for keeping the logos in the `cc-global-components` library versus relying on the downstream project to provide the logo asset?

**Comment by MuluhGodson** [comment]
> @MuluhGodson, how do the added SVG logos affect our bundle size? I'm wondering, might the logo files be included in the downstream project and passed to the `cc-logo` component as an argument? What would be some trade-offs for keeping the logos in the `cc-global-components` library versus relying on the downstream project to provide the logo asset?

Adding these SVG logos to be bundled with the components will require additional build tools, luckily Rollup provides a plugin for specifically images [@rollup/plugin-image](http://vuejscomponent.com/package?name=%40rollup%2Fplugin-image) the downside being the images are bundled as `base-64` encodings with the sizes increasing by 33% as on their documentation.

I think a good approach will be to have it in a downstream project and just receive them as arguments as you have said.

**Comment by MuluhGodson** [comment]
@brylie thanks for assigning me here. 
What about the naming conventions you suggested here: [CC Global Components Naming Convention](https://github.com/creativecommons/cc-global-components/issues/24#issuecomment-994626161) 
I think it's reasonable. So can I work following that, as it closely aligns with this task.

**Comment by brylie** [comment]
Sounds good. If we need to revise the component names again, we can publish a backward-breaking release using SemVer.

**Comment by possumbilities** [comment]
Closing this, issues related to this would have been resolved in the new Vocabulary, currently in development within [index-prototype](https://github.com/creativecommons/index-prototype)
