### ISSUE TITLE
Improve UI texts to indicate loading and failed states separately

### ISSUE THREAD

**Issue by brylie** [creativecommons/cc-global-components#25]
We can improve our menu text to indicate two separate states to the end-user:

- when loading the menu items (i.e., during the HTTP request)
- if the request failed (e.g., after a retry/timeout interval)

## Task

- [ ] add separate state variables to control the menu placeholder text for two conditions
    - [ ] loading menu items
    - [ ] HTTP error
- [ ] display a message to the end user when the menu items are being loaded
- [ ] if the HTTP request fails, display an informative message to the end-user/developer 

## Original request

> I would like a helpful message displayed (ex. "Loading Menu...") with the same formatting as the top level menu items so that the "idea of the menu" is communicated when viewed without WordPress and the same message is helpful when WordPress is available but the initial HTTP request failed, for whatever reason.

_Originally posted by @TimidRobot in https://github.com/creativecommons/cc-global-components/issues/16#issuecomment-995159763_

**Comment by MuluhGodson** [comment]
@brylie I will love to be assigned to this.

**Comment by MuluhGodson** [comment]
@cc-open-source-bot add Ready for Development

**Comment by MuluhGodson** [comment]
When the API request is sent and there is an error causing a failure. 
![chrome-capture load failed](https://user-images.githubusercontent.com/40151808/146385886-917f5c82-26f1-420e-bbdd-d394d7e6d7f9.gif)


When the API request is sent successfully.
![chrome-capture loading pass](https://user-images.githubusercontent.com/40151808/146386104-4deda283-1959-4ed5-a802-a2dc1823a48f.gif)


**Note** The retries feature has not been added here since it will be handled in a separate issue:
- [ ] https://github.com/creativecommons/cc-global-components/issues/26
