### ISSUE TITLE
Prepare 0.3.0 release

### ISSUE THREAD

**Issue by brylie** [creativecommons/cc-global-components#37]
We have some changes that are ready for release, some of which are backward incompatible. However, we have a working agreement that backward-incompatible changes are permissible for the 0.x series.

## Task

- [x] prepare a new release
- [x] ensure that known downstream projects are aware of backward-incompatible changes
- [ ] if needed, bump the major version instead of minor

**Comment by brylie** [comment]
Version 0.3.0 is published: https://www.npmjs.com/package/@creativecommons/cc-global-components/v/0.3.0
